# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssql" do
  version "4.47.0"

  on_macos do
    on_intel do
      sha256 "dff21b33a892732eb98e09607c575b1c89afe9667a22c9055b7ad96c6869b882"
      url "https://github.com/rosscartlidge/ssql/releases/download/v#{version}/ssql_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "65a2f3c0eeeacccc00357476a74f4e544101f8d2664e8feab9175f5b2a81113b"
      url "https://github.com/rosscartlidge/ssql/releases/download/v#{version}/ssql_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5483f457e3e41bfcd65e171aa997c611413f128257b01c1b3d10028cb22d2dab"
      url "https://github.com/rosscartlidge/ssql/releases/download/v#{version}/ssql_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "feb32fcead65b3e541e34afde525bb4b30f78bbfc926268ab154909d5e4fdf1a"
      url "https://github.com/rosscartlidge/ssql/releases/download/v#{version}/ssql_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ssql"
  desc "SQL-style stream processing for CSV, JSON, and more"
  homepage "https://github.com/rosscartlidge/ssql"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssql"

  # No zap stanza required

end
