# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssql" do
  version "4.113.1"

  on_macos do
    on_arm do
      sha256 "374cb834617153ae9478cdbf7bbcfe20d169748297fd51b3acbe14b881bc3d45"
      url "https://github.com/rosscartlidge/ssql/releases/download/v#{version}/ssql_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6dd0f816041c19976a14f8c7a60bbb4f8575fc71439e8d56a76fd0f92e6553a6"
      url "https://github.com/rosscartlidge/ssql/releases/download/v#{version}/ssql_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ee30aa334e2f0ead4739167d63212c1b3a7de557ccfd4a6bd0abfe641bd81317"
      url "https://github.com/rosscartlidge/ssql/releases/download/v#{version}/ssql_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "175f56cf494d292cdeebca7448e36f9c5c9447fac216c5d730ceef101f40a606"
      url "https://github.com/rosscartlidge/ssql/releases/download/v#{version}/ssql_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ssql"
  desc "SQL-style stream processing for CSV, JSON, and more"
  homepage "https://github.com/rosscartlidge/ssql"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssql"

  # No zap stanza required
end
