# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssql" do
  version "4.56.1"

  on_macos do
    on_intel do
      sha256 "7d6c26681a1ec2336309e66bc49e78153c2ba51716654d20319f4a12ab69d24c"
      url "https://github.com/rosscartlidge/ssql/releases/download/v#{version}/ssql_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a5387676bac9a2daa91e87ca1918ad40944a8907a0fd672865dde46e996fb6d"
      url "https://github.com/rosscartlidge/ssql/releases/download/v#{version}/ssql_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "062653f39dfa337d19e3a25a7aea794c6d8cda5549c39ed89ffab98e87befa50"
      url "https://github.com/rosscartlidge/ssql/releases/download/v#{version}/ssql_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0e055999f36ef5c2933f988ec33442f5d11d76beb602b41f56b2f873535e63a6"
      url "https://github.com/rosscartlidge/ssql/releases/download/v#{version}/ssql_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ssql"
  desc "SQL-style stream processing for CSV, JSON, and more"
  homepage "https://github.com/rosscartlidge/ssql"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssql"

  # No zap stanza required

end
